### ISSUE TITLE
Uninstalling user_ldap using market app leads to a broken server.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/user_ldap#115]
### Steps to reproduce

0. Having a server with market app installed and enabled.
1. Using admin user go to market.
2. Search for user_ldap app.
3. Install it.
4. Uninstall it.
5. Access the server.

### Expected behaviour
App user_ldap unsintalled. Server working correctly.

### Actual behaviour
500 errors. Server failing in ldap code.

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
current master
{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.2.1","versionstring":"10.0.2.1","edition":"Enterprise","productname":"ownCloud"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No

**Logs**
When accessing the server
```
{"reqId":"puq1JvZi5uE02eMRDztN","level":3,"time":"2017-07-17T12:48:20+00:00","remoteAddr":"HIDDEN_IP","user":"admin","app":"index","method":"GET","url":"\/index.php\/logout?requesttoken=BxYfPTEFK1VzWhQOQCxKDwMQPEZxEhZSBTJ3EhkmbDo%3D%3A1wgrhsXmD2Szsu89isH5EJp4dbCwpn4XnW1v5OPlps8%3D","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Class 'OCA\\\\User_LDAP\\\\Helper' not found\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/files_ldap_home\\\/lib\\\/Storage.php(42): OCA\\\\Files_LDAP_Home\\\\Storage::initiateLDAPAccess(Object(OC\\\\AllConfig))\\n#1 \\\/opt\\\/owncloud\\\/apps\\\/files_ldap_home\\\/lib\\\/Storage.php(150): OCA\\\\Files_LDAP_Home\\\\Storage->__construct(Array)\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/hook.php(105): OCA\\\\Files_LDAP_Home\\\\Storage::setup(Array)\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php(452): OC_Hook::emit('OC_Filesystem', 'post_initMountP...', Array)\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php(375): OC\\\\Files\\\\Filesystem::initMountPoints('admin')\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/util.php(297): OC\\\\Files\\\\Filesystem::init('admin', '\\\/admin\\\/files')\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/base.php(919): OC_Util::setupFS()\\n#7 \\\/opt\\\/owncloud\\\/index.php(49): OC::handleRequest()\\n#8 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/files_ldap_home\\\/lib\\\/Storage.php\",\"Line\":97}"}
{"reqId":"6P9H3rs7QWLCmDs1OsoS","level":3,"time":"2017-07-17T12:48:20+00:00","remoteAddr":"HIDDEN_IP","user":"admin","app":"index","method":"GET","url":"\/index.php\/undefined\/img\/notifications.svg","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Class 'OCA\\\\User_LDAP\\\\Helper' not found\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/files_ldap_home\\\/lib\\\/Storage.php(42): OCA\\\\Files_LDAP_Home\\\\Storage::initiateLDAPAccess(Object(OC\\\\AllConfig))\\n#1 \\\/opt\\\/owncloud\\\/apps\\\/files_ldap_home\\\/lib\\\/Storage.php(150): OCA\\\\Files_LDAP_Home\\\\Storage->__construct(Array)\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/hook.php(105): OCA\\\\Files_LDAP_Home\\\\Storage::setup(Array)\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php(452): OC_Hook::emit('OC_Filesystem', 'post_initMountP...', Array)\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php(375): OC\\\\Files\\\\Filesystem::initMountPoints('admin')\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/util.php(297): OC\\\\Files\\\\Filesystem::init('admin', '\\\/admin\\\/files')\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/base.php(919): OC_Util::setupFS()\\n#7 \\\/opt\\\/owncloud\\\/index.php(49): OC::handleRequest()\\n#8 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/files_ldap_home\\\/lib\\\/Storage.php\",\"Line\":97}"}
{"reqId":"4ieWGJZEW4dTVUw3v4Ze","level":3,"time":"2017-07-17T12:48:27+00:00","remoteAddr":"HIDDEN_IP","user":"admin","app":"index","method":"GET","url":"\/","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Class 'OCA\\\\User_LDAP\\\\Helper' not found\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/files_ldap_home\\\/lib\\\/Storage.php(42): OCA\\\\Files_LDAP_Home\\\\Storage::initiateLDAPAccess(Object(OC\\\\AllConfig))\\n#1 \\\/opt\\\/owncloud\\\/apps\\\/files_ldap_home\\\/lib\\\/Storage.php(150): OCA\\\\Files_LDAP_Home\\\\Storage->__construct(Array)\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/hook.php(105): OCA\\\\Files_LDAP_Home\\\\Storage::setup(Array)\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php(452): OC_Hook::emit('OC_Filesystem', 'post_initMountP...', Array)\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php(375): OC\\\\Files\\\\Filesystem::initMountPoints('admin')\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/util.php(297): OC\\\\Files\\\\Filesystem::init('admin', '\\\/admin\\\/files')\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/base.php(919): OC_Util::setupFS()\\n#7 \\\/opt\\\/owncloud\\\/index.php(49): OC::handleRequest()\\n#8 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/files_ldap_home\\\/lib\\\/Storage.php\",\"Line\":97}"}
```

### Client configuration

**Browser**
Edge

**Comment by PVince81** [comment]
@SergioBertolinSG and you didn't configure any LDAP server at all ?

**Comment by SergioBertolinSG** [comment]
No ldap server configured.

**Comment by SergioBertolinSG** [comment]
The enterprise trial mode was enabled before. I cannot reproduce it in a enterprise server with license.

**Comment by tomneedham** [comment]
It's the files_ldap_home app including an LDAP class via the autoloader

**Comment by davitol** [comment]
Reproduced in 10.0.4. AS @tomneedham said it happens when it is installed user_ldap and files_ldap_home and whe uninstall user_ldap app

**Comment by tomneedham** [comment]
It is a known inter-app dependency - no way around it at the moment.
