### ISSUE TITLE
Apliance does not work after EE apps are installed

### ISSUE THREAD

**Issue by cdamken** [owncloud/user_ldap#141]
After installed the Appliance and register the EE trial,  the owncloud does not work anymore:

```
{"reqId":"tQNBIyf9aqjHPJolh0je","level":3,"time":"2017-11-13T19:07:01+01:00","remoteAddr":"172.17.42.1","user":"owncloud","app":"index","method":"GET","url":"/owncloud/index.php/apps/e2eeshare/ajax/preferences.php?app=e2eeshare&key=key_server_url&defaultValue=&action=getValue","message":"Exception: {"Exception":"TypeError","Message":"Argument 4 passed to OCA\User_LDAP\User\Manager::__construct() must implement interface OCP\IAvatarManager, null given, called in /var/www/owncloud/apps/user_ldap/lib/Proxy.php on line 77","Code":0,"Trace":"
#0 /var/www/owncloud/apps/user_ldap/lib/Proxy.php(77): OCA\User_LDAP\User\Manager->__construct(Object(OC\AllConfig), Object(OCA\User_LDAP\FilesystemHelper), Object(OCA\User_LDAP\LogWrapper), NULL, Object(OCP\Image), NULL, NULL)
#1 /var/www/owncloud/apps/user_ldap/lib/Proxy.php(91): OCA\User_LDAP\Proxy->addAccess('s01')
#2 /var/www/owncloud/apps/user_ldap/lib/User_Proxy.php(48): OCA\User_LDAP\Proxy->getAccess('s01')
#3 /var/lib/univention-appcenter/apps/owncloud/data/custom/files_ldap_home/lib/LDAPReader.php(39): OCA\User_LDAP\User_Proxy->__construct(Array, Object(OCA\User_LDAP\LDAP), Object(OC\AllConfig))
#4 /var/lib/univention-appcenter/apps/owncloud/data/custom/files_ldap_home/lib/Storage.php(100): OCA\Files_LDAP_Home\LDAPReader->__construct(Array, Object(OC\AllConfig))
#5 /var/lib/univention-appcenter/apps/owncloud/data/custom/files_ldap_home/lib/Storage.php(42): OCA\Files_LDAP_Home\Storage::initiateLDAPAccess(Object(OC\AllConfig))
#6 /var/lib/univention-appcenter/apps/owncloud/data/custom/files_ldap_home/lib/Storage.php(150): OCA\Files_LDAP_Home\Storage->__construct(Array)
#7 /var/www/owncloud/lib/private/legacy/hook.php(105): OCA\Files_LDAP_Home\Storage::setup(Array)
#8 /var/www/owncloud/lib/private/Files/Filesystem.php(452): OC_Hook::emit('OC_Filesystem', 'post_initMountP...', Array)
#9 /var/www/owncloud/lib/private/Files/Node/Root.php(348): OC\Files\Filesystem::initMountPoints('owncloud')
#10 /var/www/owncloud/lib/private/Server.php(943): OC\Files\Node\Root->getUserFolder('owncloud')
#11 /var/lib/univention-appcenter/apps/owncloud/data/custom/e2eeshare/lib/AppInfo/Application.php(33): OC\Server->getUserFolder()
#12 /var/www/owncloud/lib/composer/pimple/pimple/src/Pimple/Container.php(113): OCA\E2eeShare\AppInfo\Application->OCA\E2eeShare\AppInfo\{closure}(Object(OC\AppFramework\DependencyInjection\DIContainer))
#13 /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(111): Pimple\Container->offsetGet('E2eeShare')
#14 /var/lib/univention-appcenter/apps/owncloud/data/custom/e2eeshare/lib/AppInfo/Application.php(29): OC\AppFramework\Utility\SimpleContainer->query('E2eeShare')
#15 /var/www/owncloud/lib/composer/pimple/pimple/src/Pimple/Container.php(113): OCA\E2eeShare\AppInfo\Application->OCA\E2eeShare\AppInfo\{closure}(Object(OC\AppFramework\DependencyInjection\DIContainer))
#16 /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(111): Pimple\Container->offsetGet('E2eeHooks')
#17 /var/lib/univention-appcenter/apps/owncloud/data/custom/e2eeshare/appinfo/app.php(26): OC\AppFramework\Utility\SimpleContainer->query('E2eeHooks')
#18 /var/www/owncloud/lib/private/legacy/app.php(213): require_once('/var/lib/univen...')
#19 /var/www/owncloud/lib/private/legacy/app.php(164): OC_App::requireAppFile('e2eeshare')
#20 /var/www/owncloud/lib/private/legacy/app.php(121): OC_App::loadApp('e2eeshare')
#21 /var/www/owncloud/lib/private/legacy/util.php(145): OC_App::loadApps(Array)
#22 /var/www/owncloud/lib/private/Files/Filesystem.php(265): OC_Util::setupFS('')
#23 /var/www/owncloud/lib/private/Server.php(220): OC\Files\Filesystem::getMountManager(NULL)
#24 /var/www/owncloud/lib/composer/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#25 /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(111): Pimple\Container->offsetGet('RootFolder')
#26 /var/www/owncloud/lib/private/ServerContainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('RootFolder')
#27 /var/www/owncloud/lib/private/Server.php(914): OC\ServerContainer->query('RootFolder')
#28 /var/www/owncloud/lib/private/Server.php(413): OC\Server->getRootFolder()
#29 /var/www/owncloud/lib/composer/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#30 /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(111): Pimple\Container->offsetGet('AvatarManager')
#31 /var/www/owncloud/lib/private/ServerContainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('AvatarManager')
#32 /var/www/owncloud/lib/private/Server.php(905): OC\ServerContainer->query('AvatarManager')
#33 /var/www/owncloud/apps/user_ldap/lib/Proxy.php(70): OC\Server->getAvatarManager()
#34 /var/www/owncloud/apps/user_ldap/lib/Proxy.php(91): OCA\User_LDAP\Proxy->addAccess('s01')
#35 /var/www/owncloud/apps/user_ldap/lib/User_Proxy.php(48): OCA\User_LDAP\Proxy->getAccess('s01')
#36 /var/www/owncloud/apps/user_ldap/appinfo/app.php(36): OCA\User_LDAP\User_Proxy->__construct(Array, Object(OCA\User_LDAP\LDAP), Object(OC\AllConfig))
#37 /var/www/owncloud/lib/private/legacy/app.php(213): require_once('/var/www/ownclo...')
#38 /var/www/owncloud/lib/private/legacy/app.php(164): OC_App::requireAppFile('user_ldap')
#39 /var/www/owncloud/lib/private/legacy/app.php(121): OC_App::loadApp('user_ldap')
#40 /var/www/owncloud/lib/base.php(898): OC_App::loadApps(Array)
#41 /var/www/owncloud/index.php(56): OC::handleRequest()
#42 {main}","File":"/var/www/owncloud/apps/user_ldap/lib/User/Manager.php","Line":84}"}
{"reqId":"Qz0bho9lGVZEh5z0zF8X","level":3,"time":"2017-11-13T19:07:01+01:00","remoteAddr":"172.17.42.1","user":"owncloud","app":"PHP","method":"GET","url":"/owncloud/ocs/v2.php/apps/e2eeshare/api/v1/checkLicense?format=json","message":"TypeError: Argument 4 passed to OCA\User_LDAP\User\Manager::__construct() must implement interface OCP\IAvatarManager, null given, called in /var/www/owncloud/apps/user_ldap/lib/Proxy.php on line 77 at /var/www/owncloud/apps/user_ldap/lib/User/Manager.php#84"}
```

As workaround you can remove the `e2eeshare` and then it works

@butonic @tomneedham @patrickjahns

**Comment by patrickjahns** [comment]
As discussed - this is not related to `user_ldap` - it is related to 3rd party app `e2eeshare`. 
Fixed by uninstalling / disabling that application

**Comment by patrickjahns** [comment]
Reopening - invested some more time - this is related to a combination of user_ldap and files_ldap_home that is somehow triggered by e2eeshare app

**Comment by IljaN** [comment]
10.0.4 appliance breaks with this error https://github.com/owncloud/user_ldap/issues/141, as a workaround users_ldap can be disabled before installing enterprise bundle and then enabled again

10.0.7 works

**Comment by patrickjahns** [comment]
Please confirm that e2eeshare app is not default installed with the bundle ...

**Comment by voroyam** [comment]
it is, confirmed

**Comment by IljaN** [comment]
@voroyam / @patrickjahns close?

**Comment by voroyam** [comment]
a yes from me
