### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by INHack20** [owncloud/user_ldap#152]
Translating to english:

He is sending the trace from an error after reviewing the code the found some valitations that was returning null for some elements.

Original Text:
```
Hola le envio, un error que me ocurrió al probar el LDAP, después de revisar el código fuente solo faltaban unas validaciones cuando algunos elementos se retornaban nulos.

Le envio el trazo para que actualicen el código.

Gracias.
``` 
``` 
{"reqId":"4tzWPw922GeZRXvkWZr6","level":3,"time":"2017-11-27T03:56:48+00:00","remoteAddr":"172.16.63.243","user":"--","app":"index","method":"POST","url":"/owncloud/index.php/login?user=carlos.mendoza","message":"Exception: {"Exception":"Error","Message":"Call to a member function getSearchTerms() on null","Code":0,"Trace":"
#0 [internal function]: OCA\User_LDAP\User_LDAP->getSearchTerms('79380929-4AB4-4...')
#1 /var/www/owncloud/apps/user_ldap/lib/User_Proxy.php(82): call_user_func_array(Array, Array)
#2 /var/www/owncloud/apps/user_ldap/lib/Proxy.php(140): OCA\User_LDAP\User_Proxy->walkBackends('79380929-4AB4-4...', 'getSearchTerms', Array)
#3 /var/www/owncloud/apps/user_ldap/lib/User_Proxy.php(60): OCA\User_LDAP\Proxy->handleRequest('79380929-4AB4-4...', 'getSearchTerms', Array)
#4 /var/www/owncloud/lib/private/User/Manager.php(443): OCA\User_LDAP\User_Proxy->getSearchTerms('79380929-4AB4-4...')
#5 /var/www/owncloud/lib/private/User/Manager.php(220): OC\User\Manager->newAccount('79380929-4AB4-4...', Object(OCA\User_LDAP\User_Proxy))
#6 /var/www/owncloud/lib/private/User/Session.php(467): OC\User\Manager->checkPassword(*** sensitive parameters replaced ***)
#7 /var/www/owncloud/lib/private/User/Session.php(301): OC\User\Session->loginWithPassword(*** sensitive parameters replaced ***)
#8 /var/www/owncloud/core/Controller/LoginController.php(201): OC\User\Session->login(*** sensitive parameters replaced ***)
#9 [internal function]: OC\Core\Controller\LoginController->tryLogin(*** sensitive parameters replaced ***)
#10 /var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php(159): call_user_func_array(Array, Array)
#11 /var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php(89): OC\AppFramework\Http\Dispatcher->executeController(Object(OC\Core\Controller\LoginController), 'tryLogin')
#12 /var/www/owncloud/lib/private/AppFramework/App.php(98): OC\AppFramework\Http\Dispatcher->dispatch(Object(OC\Core\Controller\LoginController), 'tryLogin')
#13 /var/www/owncloud/lib/private/AppFramework/Routing/RouteActionHandler.php(46): OC\AppFramework\App::main('LoginController', 'tryLogin', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#14 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#15 /var/www/owncloud/lib/private/Route/Router.php(307): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
#16 /var/www/owncloud/lib/base.php(928): OC\Route\Router->match('/login')
#17 /var/www/owncloud/index.php(56): OC::handleRequest()
#18 {main}","File":"/var/www/owncloud/apps/user_ldap/lib/User_LDAP.php","Line":433}"}
```

**Comment by cdamken** [comment]
@INHack20  Por favor escriben en inglés.  Así todos los desarrolladores pueden ayudar.

Please write in English, this way everybody can help you.
