### ISSUE TITLE
Active directory user cannot log into owncloud when there is another instance configured

### ISSUE THREAD

**Issue by davitol** [owncloud/user_ldap#155]
**Steps to reproduce:**

1. As admin set up an openLDAP configuration
2. As admin set up an AD configuration
3. Try to log in with a user of the Active Directory

**Expected behavior**

The user can log into the ownCloud instance

**Current behavior**

The user can NOT log into the ownCloud instance

```
{"reqId":"tcrn8eOiwMb0iLxd1KNI","level":3,"time":"2017-11-29T11:24:33+00:00","remoteAddr":"85.57.168.79","user":"--","app":"user_ldap","method":"POST","url":"\/index.php\/login?user=GChapman","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"No user available for the given login name on XXXXXXXXXX:2007\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/User_LDAP.php(140): OCA\\\\User_LDAP\\\\User\\\\Manager->getLDAPUserByLoginName('GChapman')\\n#1 [internal function]: OCA\\\\User_LDAP\\\\User_LDAP->checkPassword(*** sensitive parameters replaced ***)\\n#2 \\\/opt\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/User_Proxy.php(75): call_user_func_array(Array, Array)\\n#3 \\\/opt\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/Proxy.php(140): OCA\\\\User_LDAP\\\\User_Proxy->walkBackends('GChapman', 'checkPassword', Array)\\n#4 \\\/opt\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/User_Proxy.php(180): OCA\\\\User_LDAP\\\\Proxy->handleRequest('GChapman', 'checkPassword', Array)\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/User\\\/Manager.php(215): OCA\\\\User_LDAP\\\\User_Proxy->checkPassword(*** sensitive parameters replaced ***)\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(467): OC\\\\User\\\\Manager->checkPassword(*** sensitive parameters replaced ***)\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(298): OC\\\\User\\\\Session->loginWithPassword(*** sensitive parameters replaced ***)\\n#8 \\\/opt\\\/owncloud\\\/core\\\/Controller\\\/LoginController.php(201): OC\\\\User\\\\Session->login(*** sensitive parameters replaced ***)\\n#9 [internal function]: OC\\\\Core\\\\Controller\\\\LoginController->tryLogin(*** sensitive parameters replaced ***)\\n#10 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#11 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')\\n#12 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(98): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')\\n#13 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('LoginController', 'tryLogin', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#14 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#15 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#16 \\\/opt\\\/owncloud\\\/lib\\\/base.php(929): OC\\\\Route\\\\Router->match('\\\/login')\\n#17 \\\/opt\\\/owncloud\\\/index.php(56): OC::handleRequest()\\n#18 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/User\\\/Manager.php\",\"Line\":522}"}
{"reqId":"tcrn8eOiwMb0iLxd1KNI","level":2,"time":"2017-11-29T11:24:33+00:00","remoteAddr":"85.57.168.79","user":"--","app":"core","method":"POST","url":"\/index.php\/login?user=GChapman","message":"Login failed: 'GChapman' (Remote IP: '85.57.168.79')"}
{"reqId":"ZRHdBQeP1PtUJLtPZYgA","level":0,"time":"2017-11-29T11:24:33+00:00","remoteAddr":"85.57.168.79","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Started background job of class : OCA\\Files\\BackgroundJob\\DeleteOrphanedItems with arguments : "}
{"reqId":"ZRHdBQeP1PtUJLtPZYgA","level":0,"time":"2017-11-29T11:24:33+00:00","remoteAddr":"85.57.168.79","user":"--","app":"DeleteOrphanedItems","method":"GET","url":"\/cron.php","message":"0 orphaned system tag relations deleted"}
{"reqId":"ZRHdBQeP1PtUJLtPZYgA","level":0,"time":"2017-11-29T11:24:33+00:00","remoteAddr":"85.57.168.79","user":"--","app":"DeleteOrphanedItems","method":"GET","url":"\/cron.php","message":"0 orphaned user tag relations deleted"}
{"reqId":"ZRHdBQeP1PtUJLtPZYgA","level":0,"time":"2017-11-29T11:24:33+00:00","remoteAddr":"85.57.168.79","user":"--","app":"DeleteOrphanedItems","method":"GET","url":"\/cron.php","message":"0 orphaned comments deleted"}
{"reqId":"ZRHdBQeP1PtUJLtPZYgA","level":0,"time":"2017-11-29T11:24:33+00:00","remoteAddr":"85.57.168.79","user":"--","app":"DeleteOrphanedItems","method":"GET","url":"\/cron.php","message":"0 orphaned comment read marks deleted"}
{"reqId":"ZRHdBQeP1PtUJLtPZYgA","level":0,"time":"2017-11-29T11:24:33+00:00","remoteAddr":"85.57.168.79","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Finished background job, the job took : 0 seconds, this job is an instance of class : OCA\\Files\\BackgroundJob\\DeleteOrphanedItems with arguments : "}
```

**Comment by butonic** [comment]
@davitol can you post the ldap config from the config report? I had to enable the second configuration explicitly, but it works as expected and I can login with users from both ldap servers. I can even shutdown the first ldap server and users from the second ldap server are still able to log in.

this is on the `release/0.10.0` branch

**Comment by davitol** [comment]
Retested with release/0.10.0  and I cannot reproduce it, so the steps detailed in this ticket are not an issue. Let's close the ticket. Sorry for the noise
