### ISSUE TITLE
ownCloud shares are removed temporarily when LDAP server is not available

### ISSUE THREAD

**Issue by agross** [owncloud/user_ldap#176]
Today I needed to reboot my LDAP server. The reboot caused the LDAP connection to be broken, but what made matters worse is that shares created by LDAP users are removed for non-LDAP enabled accounts.

Consider this setup:
1. User `A` is authenticated against LDAP
1. User `B` has a normal ownCloud account
1. User `A` shares a directory `D` to user `B`
1. User `B` syncs using his or her ownCloud client , `D` is downloaded
1. The LDAP server is rebooted, hence the connection is lost and `A` is unable to authenticate
1. **The ownCloud client of user `B` notifies the user that `D` has been unshared and deletes `D` from disk**
1. LDAP server comes back online
1. Shares are restored
1. User `B` needs to redownload `D`

The problem is that `D` contains about 20 GB of files, and these 20GB are added to our allotted network bandwidth. Consider you need to reboot LDAP quite often, it always causes those 20GB to be deleted and redownloaded a couple of minutes later.

**Comment by PVince81** [comment]
Expected behavior. share is still mounted but inaccessible with "503 Storage Not Available"

**Comment by PVince81** [comment]
@butonic @tomneedham

**Comment by agross** [comment]
Ok, but does step 6 really need to delete all files from disk? IMHO Storage Not Available does not mean that the share was actually removed.

**Comment by PVince81** [comment]
Internally "Storage Not Available" tells any clients to "leave everything as it is" so no deletion would happen.

**Comment by PVince81** [comment]
and with "Storage Not Available" it is meant "Storage Temporarily Not Available, Please Try Again Later"

**Comment by agross** [comment]
If I understand you correctly this is a client issue?

**Comment by PVince81** [comment]
No. The problem is likely that the server does not correctly return the status code "503 Storage Temporarily Not Available" for said folder or even fails to mount them to the filesystem view.

The clients do not see the folders any more so they believe they are deleted so they delete it locally.

The correct behavior is to keep the mounts visible (incoming shares are mounts) but when explored they should return the 503 error.

**Comment by agross** [comment]
OK, who should I contact about this? owncloud/core?

**Comment by PVince81** [comment]
It is not clear yet whether this is a core issue or LDAP. It all depends how LDAP users are exposed at the moment the server becomes unavialable.

I'd expect the users to continue existing anyway due to the oc_account tables...

... wait a minute, you didn't post your ownCloud version ? I'm talking about OC 10.0 where I expect this problem to be resolved already with the oc_accounts table which was specifically introduced to avoid this kind of problems.

Please use the issue template https://raw.githubusercontent.com/owncloud/core/master/.github/issue_template.md

**Comment by agross** [comment]
Talking about 10.0.4. The table exists.

```sh
$ docker exec -it owncloud_mariadb_1 mysql -uroot '-psomething' -e 'select * from owncloud.oc_accounts where user_id="agross";'
+----+-------------------------+---------+---------------+----------------+-------+------------+--------------------------+---------------------------+-------+
| id | email                   | user_id | lower_user_id | display_name   | quota | last_login | backend                  | home                      | state |
+----+-------------------------+---------+---------------+----------------+-------+------------+--------------------------+---------------------------+-------+
|  1 | agross@therightstuff.de | agross  | agross        | Alexander Gro� | NULL  | 1517698680 | OCA\User_LDAP\User_Proxy | /var/www/html/data/agross |     1 |
+----+-------------------------+---------+---------------+----------------+-------+------------+--------------------------+---------------------------+-------+
```

FYI, the issue template in core does not apply to users_ldap.

**Comment by PVince81** [comment]
The table should contain the users from the LDAP users that disappeared when the LDAP server went away.

Did you also setup the cron job that runs `occ user:sync` as per documentation ?

I wonder whether said command properly detects missing servers and doesn't try to sync the disappeared users. Maybe the cron output from that moment contains some clues ?

**Comment by agross** [comment]
1. I wasn't aware of `occ user:sync` and couldn't find any information on this doing a quick search in the [admin docs](https://doc.owncloud.org/server/9.1/admin_manual/configuration_user/user_auth_ldap.html#configuration), [here](https://doc.owncloud.org/server/latest/admin_manual/installation/deployment_recommendations.html) or [here](https://doc.owncloud.org/server/latest/admin_manual/search.html?q=users%3Async). Where is that documented?
1. I don't really care about added users that `occ users:sync` might add to oC, I guess sync allows to share stuff with users that never logged in, but we don't need that ATM.
1. It's just that the LDAP server connection is interrupted that causes shares to be considered gone by either the server or the client.

**Comment by patrickjahns** [comment]
@agross 
you've searched in the 9.1 docs for the `user:sync` - you find it documented here:
https://doc.owncloud.org/server/latest/admin_manual/configuration/server/occ_command.html#syncing-user-accounts-label

**Comment by agross** [comment]
@patrickjahns Thanks. As far as I understand it, syncing users is optional with a small number of users. We have about 10, which I consider small.

FYI, this is what I tried earlier today to find the docs you mentioned. And yes, I was searching the latest docs.

https://doc.owncloud.org/server/latest/admin_manual/search.html?q=user%3A+sync

**Comment by butonic** [comment]
I just failed to reproduce this. When ldap is down `A` cannot login. `B` being a database user still can. He can also up and download files into `D`.

@agross What you describe sounds like `B` was disabled. That only happens when syncing users. Any errors in the logfile? Can you send a log file with debugging enabled? Is `D` a federated share?

**Comment by agross** [comment]
```
{"reqId":"5a0e0645-e8aa-49fe-b927-8f90d27e0b47","level":3,"time":"2018-02-07T22:55:59+00:00","remoteAddr":"172.19.0.1","user":"agross","app":"user_ldap","method":"PROPFIND","url":"\/remote.php\/dav\/files\/agross\/","message":"Exception: {\"Exception\":\"OC\\\\ServerNotAvailableException\",\"Message\":\"Lost connection to LDAP server.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/apps\\\/user_ldap\\\/lib\\\/LDAP.php(279): OCA\\\\User_LDAP\\\\LDAP->postFunctionCall()\\n#1 \\\/var\\\/www\\\/html\\\/apps\\\/user_ldap\\\/lib\\\/LDAP.php(43): OCA\\\\User_LDAP\\\\LDAP->invokeLDAPMethod('bind', Resource id #70, 'uid=owncloud,cn...', 'bind password...')\\n#2 \\\/var\\\/www\\\/html\\\/apps\\\/user_ldap\\\/lib\\\/Connection.php(540): OCA\\\\User_LDAP\\\\LDAP->bind(Resource id #70, 'uid=owncloud,cn...', 'HIs$9X4ECR?!I+V...')\\n#3 \\\/var\\\/www\\\/html\\\/apps\\\/user_ldap\\\/lib\\\/Connection.php(167): OCA\\\\User_LDAP\\\\Connection->establishConnection()\\n#4 \\\/var\\\/www\\\/html\\\/apps\\\/user_ldap\\\/lib\\\/Connection.php(176): OCA\\\\User_LDAP\\\\Connection->init()\\n#5 \\\/var\\\/www\\\/html\\\/apps\\\/user_ldap\\\/lib\\\/Access.php(989): OCA\\\\User_LDAP\\\\Connection->getConnectionResource()\\n#6 \\\/var\\\/www\\\/html\\\/apps\\\/user_ldap\\\/lib\\\/Access.php(1156): OCA\\\\User_LDAP\\\\Access->executeSearch('(&(|(uid=agross...', Array, Array, NULL, NULL)\\n#7 \\\/var\\\/www\\\/html\\\/apps\\\/user_ldap\\\/lib\\\/Access.php(925): OCA\\\\User_LDAP\\\\Access->search('(&(|(uid=agross...', Array, Array, NULL, NULL)\\n#8 \\\/var\\\/www\\\/html\\\/apps\\\/user_ldap\\\/lib\\\/Access.php(821): OCA\\\\User_LDAP\\\\Access->searchUsers('(&(|(uid=agross...', Array, NULL, NULL)\\n#9 \\\/var\\\/www\\\/html\\\/apps\\\/user_ldap\\\/lib\\\/Access.php(794): OCA\\\\User_LDAP\\\\Access->fetchListOfUsers('(&(|(uid=agross...', Array)\\n#10 \\\/var\\\/www\\\/html\\\/apps\\\/user_ldap\\\/lib\\\/User\\\/Manager.php(526): OCA\\\\User_LDAP\\\\Access->fetchUsersByLoginName('agross', Array)\\n#11 \\\/var\\\/www\\\/html\\\/apps\\\/user_ldap\\\/lib\\\/User_LDAP.php(140): OCA\\\\User_LDAP\\\\User\\\\Manager->getLDAPUserByLoginName('agross')\\n#12 [internal function]: OCA\\\\User_LDAP\\\\User_LDAP->checkPassword(*** sensitive parameters replaced ***)\\n#13 \\\/var\\\/www\\\/html\\\/apps\\\/user_ldap\\\/lib\\\/User_Proxy.php(75): call_user_func_array(Array, Array)\\n#14 \\\/var\\\/www\\\/html\\\/apps\\\/user_ldap\\\/lib\\\/Proxy.php(140): OCA\\\\User_LDAP\\\\User_Proxy->walkBackends('agross', 'checkPassword', Array)\\n#15 \\\/var\\\/www\\\/html\\\/apps\\\/user_ldap\\\/lib\\\/User_Proxy.php(180): OCA\\\\User_LDAP\\\\Proxy->handleRequest('agross', 'checkPassword', Array)\\n#16 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/User\\\/Manager.php(215): OCA\\\\User_LDAP\\\\User_Proxy->checkPassword(*** sensitive parameters replaced ***)\\n#17 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/User\\\/BasicAuthModule.php(49): OC\\\\User\\\\Manager->checkPassword(*** sensitive parameters replaced ***)\\n#18 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/User\\\/Session.php(883): OC\\\\User\\\\BasicAuthModule->auth(Object(OC\\\\AppFramework\\\\Http\\\\Request))\\n#19 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Auth.php(116): OC\\\\User\\\\Session->verifyAuthHeaders(Object(OC\\\\AppFramework\\\\Http\\\\Request))\\n#20 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php(105): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Auth->validateUserPass(*** sensitive parameters replaced ***)\\n#21 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Auth.php(246): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->check(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#22 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Auth.php(150): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Auth->auth(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#23 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(201): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Auth->check(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#24 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(150): Sabre\\\\DAV\\\\Auth\\\\Plugin->check(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#25 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#26 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#27 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#28 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#29 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Server.php(256): Sabre\\\\DAV\\\\Server->exec()\\n#30 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#31 \\\/var\\\/www\\\/html\\\/remote.php(165): require_once('\\\/var\\\/www\\\/html\\\/a...')\\n#32 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/apps\\\/user_ldap\\\/lib\\\/LDAP.php\",\"Line\":310}"}

{"reqId":"5a0e0645-e8aa-49fe-b927-8f90d27e0b47","level":4,"time":"2018-02-07T22:58:10+00:00","remoteAddr":"172.19.0.1","user":"agross","app":"webdav","method":"PROPFIND","url":"\/remote.php\/dav\/files\/agross\/","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 OC\\\\ServerNotAvailableException: Lost connection to LDAP server.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(201): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Auth->check(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(150): Sabre\\\\DAV\\\\Auth\\\\Plugin->check(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#5 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Server.php(256): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/html\\\/remote.php(165): require_once('\\\/var\\\/www\\\/html\\\/a...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Auth.php\",\"Line\":157,\"User\":\"agross\"}"}
```

This is what gets logged.

> What you describe sounds like `B` was disabled.

All I can say is that `B` no longer sees the share (confirmed using the web UI) and his Windows client deletes the `D` from disk.

**Comment by patrickjahns** [comment]
@agross 
> syncing users is optional with a small number of users. We have about 10, which I consider small.

Slight caveat: if they have never logged in, they won't be available for any sharing - hence the recommendation of syncing them straight away.

**Comment by agross** [comment]
> if they have never logged in, they won't be available for any sharing

I know. As I said, not a problem for us. Our user count is rather stable (changed once in a few years).

**Comment by agross** [comment]
`user_ldap: 0.10.0`
