### ISSUE TITLE
[10.Beta] user sync does not support Chinese characters. 

### ISSUE THREAD

**Issue by cdamken** [owncloud/user_ldap#74]
Using ldap://docker.oc.solidgear.es

```
sudo -u www-data php occ user:sync "OCA\User_LDAP\User_LDAP"
Insert new and update existing users ...
    0/1010 [>---------------------------]   0%

  [InvalidArgumentException]
  uid for 'uid=小池_憲明,ou=people,dc=owncloudqa,dc=com' must not be an empty
   string!


user:sync [-l|--list] [--] [<backend-class>]

root@cloudine:/var/www/html/owncloud#
``` 

@DeepDiver1975 @davitol @jvillafanez

**Comment by PVince81** [comment]
I assume such users did work correctly in 9.1 ?

**Comment by davitol** [comment]
In 9.1.5 you are able to log in with a LDAP user with chinese characters


![screen shot 2017-04-19 at 15 23 52](https://cloud.githubusercontent.com/assets/10596560/25182250/4eb61ee2-2514-11e7-9849-0608c4df1b5a.png)

**Comment by pako81** [comment]
![image](https://cloud.githubusercontent.com/assets/12248713/25182287/6d537264-2514-11e7-932e-dd98bbb9eed1.png)

**Comment by cdamken** [comment]
That's the LDAP server from QA

Yes, It worked with 9.1.4 

The only stuff that we can see is the username is -

**Comment by jvillafanez** [comment]
I guess the relevant code is https://github.com/owncloud/user_ldap/blob/master/lib/Access.php#L1202 which is used around https://github.com/owncloud/user_ldap/blob/master/lib/Access.php#L566

I think the reason behind that substitution is that the username will be usually used to create the user's home in the ownCloud's data folder. We might not be able to guarantee the FS supports utf-8 chars as files / folder names.

I guess you've set the "uid" as username attribute in the LDAP's expert tab. If you have users with non-ascii chars, I'd recommend to either leave it empty and use the default, or use any other attribute which only has ascii chars and there are no duplicates.

**Comment by PVince81** [comment]
> We might not be able to guarantee the FS supports utf-8 chars as files / folder names.

But it did work in 9.1, so his FS is likely supporting it. Maybe PHP env issue causing trouble ?

**Comment by jvillafanez** [comment]
Works for me, at least until I start to do weird things.

@cdamken what's your configuration?

**Comment by DeepDiver1975** [comment]
@cdamken mysql? 4byte enabled?

**Comment by butonic** [comment]
@cdamken show us the ldap config pls. It seems the ldap uid attrubte is used as the userid. We should recommend always using the uuid attribute, eg objectguid, entryuuid ... or maybe even prevent changing it to something else in the future. might need some thougt on how to migrate, but anything else but the uuid creates problems. the home folder naming rule attribute can be used to use a more readable dir ... but I see no good reason to change it if we add an occ command that returns the homedir path if given a userid. then admins don't need to leave the cli to get the home folder for a userid

another thing is that logs are hard to understand if only a uuid like userid is logged. can be easily solved if we added the displayname to the log as well. but I am leaving the topic...

So actually, I think it is the right thing to throw an exception here, because the sanitization wiped the userid derived from uid. -> choose a different userid attribute.

**Comment by cdamken** [comment]
ldap://docker.oc.solidgear.es
user: cn=admin,dc=owncloudqa,dc=com
password: owncloud123

Tested with 10.RC2:
```
root@cloudine:~# sudo -u www-data php /var/www/html/owncloud/occ user:sync "OCA\User_LDAP\User_Proxy"
Insert new and update existing users ...
    0/1010 [>---------------------------]   0%

  [InvalidArgumentException]
  uid for 'uid=小池_憲明,ou=people,dc=owncloudqa,dc=com' must not be an empty string!


user:sync [-l|--list] [--] [<backend-class>]

root@cloudine:~# sudo -u www-data php /var/www/html/owncloud/occ ldap:show-config
+-------------------------------+-----------------------------------------------------------------------+
| Configuration                 | s01                                                                   |
+-------------------------------+-----------------------------------------------------------------------+
| hasMemberOfFilterSupport      |                                                                       |
| hasPagedResultSupport         |                                                                       |
| homeFolderNamingRule          |                                                                       |
| lastJpegPhotoLookup           | 0                                                                     |
| ldapAgentName                 | cn=admin,dc=owncloudqa,dc=com                                         |
| ldapAgentPassword             | ***                                                                   |
| ldapAttributesForGroupSearch  |                                                                       |
| ldapAttributesForUserSearch   |                                                                       |
| ldapBackupHost                |                                                                       |
| ldapBackupPort                |                                                                       |
| ldapBase                      | dc=owncloudqa,dc=com                                                  |
| ldapBaseGroups                | dc=owncloudqa,dc=com                                                  |
| ldapBaseUsers                 | dc=owncloudqa,dc=com                                                  |
| ldapCacheTTL                  | 600                                                                   |
| ldapConfigurationActive       | 1                                                                     |
| ldapDynamicGroupMemberURL     |                                                                       |
| ldapEmailAttribute            |                                                                       |
| ldapExperiencedAdmin          | 0                                                                     |
| ldapExpertUUIDGroupAttr       |                                                                       |
| ldapExpertUUIDUserAttr        | uid                                                                   |
| ldapExpertUsernameAttr        | uid                                                                   |
| ldapGroupDisplayName          | cn                                                                    |
| ldapGroupFilter               | (|(cn=Box4)(cn=Box5)(cn=Box6)(cn=Box7)(cn=Box10)(cn=Box11)(cn=Box12)) |
| ldapGroupFilterGroups         | Box4;Box5;Box6;Box7;Box10;Box11;Box12                                 |
| ldapGroupFilterMode           | 0                                                                     |
| ldapGroupFilterObjectclass    |                                                                       |
| ldapGroupMemberAssocAttr      | memberUid                                                             |
| ldapHost                      | ldap://docker.oc.solidgear.es                                         |
| ldapIgnoreNamingRules         |                                                                       |
| ldapLoginFilter               | (&(|(objectclass=inetOrgPerson))(uid=%uid))                           |
| ldapLoginFilterAttributes     |                                                                       |
| ldapLoginFilterEmail          | 0                                                                     |
| ldapLoginFilterMode           | 0                                                                     |
| ldapLoginFilterUsername       | 1                                                                     |
| ldapNestedGroups              | 0                                                                     |
| ldapOverrideMainServer        |                                                                       |
| ldapPagingSize                | 500                                                                   |
| ldapPort                      | 389                                                                   |
| ldapQuotaAttribute            |                                                                       |
| ldapQuotaDefault              |                                                                       |
| ldapTLS                       | 0                                                                     |
| ldapUserDisplayName           | displayName                                                           |
| ldapUserDisplayName2          |                                                                       |
| ldapUserFilter                | (|(objectclass=inetOrgPerson))                                        |
| ldapUserFilterGroups          |                                                                       |
| ldapUserFilterMode            | 0                                                                     |
| ldapUserFilterObjectclass     | inetOrgPerson                                                         |
| ldapUuidGroupAttribute        | auto                                                                  |
| ldapUuidUserAttribute         | auto                                                                  |
| turnOffCertCheck              | 0                                                                     |
| useMemberOfToDetectMembership | 1                                                                     |
+-------------------------------+-----------------------------------------------------------------------+
root@cloudine:~#
```

**Comment by cdamken** [comment]
I tested the same LDAP without adding `UID` in the expert tab and works. but uses uuid

**Comment by cdamken** [comment]
Im checking in 9.1.5 and theoretically should work, but it crashes (In docker) 

```
{"reqId":"O2+v6WgeA3uHoZG/ASdv","remoteAddr":"172.17.0.1","app":"index","message":"Exception: {"Exception":"InvalidArgumentException","Message":"uid for 'uid=\u5c0f\u6c60_\u61b2\u660e,ou=people,dc=owncloudqa,dc=com' must not be an empty string!","Code":0,"Trace":"
#0 /var/www/html/owncloud/apps/user_ldap/lib/User/Manager.php(120): OCA\User_LDAP\User\User->__construct('', 'uid=\xE5\xB0\x8F\xE6\xB1\xA0_\xE6\x86\xB2\xE6...', Object(OCA\User_LDAP\Access), Object(OC\AllConfig), Object(OCA\User_LDAP\FilesystemHelper), Object(OCP\Image), Object(OCA\User_LDAP\LogWrapper), Object(OC\AvatarManager), Object(OC\User\Manager))
#1 /var/www/html/owncloud/apps/user_ldap/lib/User/Manager.php(211): OCA\User_LDAP\User\Manager->createAndCache('uid=\xE5\xB0\x8F\xE6\xB1\xA0_\xE6\x86\xB2\xE6...', '')
#2 /var/www/html/owncloud/apps/user_ldap/lib/User/Manager.php(237): OCA\User_LDAP\User\Manager->createInstancyByUserName('')
#3 /var/www/html/owncloud/apps/user_ldap/lib/Access.php(730): OCA\User_LDAP\User\Manager->get('')
#4 /var/www/html/owncloud/apps/user_ldap/lib/Access.php(708): OCA\User_LDAP\Access->batchApplyUserAttributes(Array)
#5 /var/www/html/owncloud/apps/user_ldap/lib/User_LDAP.php(191): OCA\User_LDAP\Access->fetchListOfUsers('(&(|(objectclas...', Array, 50, 0)
#6 /var/www/html/owncloud/lib/private/User/Manager.php(222): OCA\User_LDAP\User_LDAP->getUsers('', 50, 0)
#7 /var/www/html/owncloud/settings/Controller/UsersController.php(251): OC\User\Manager->search('', 50, 0)
#8 [internal function]: OC\Settings\Controller\UsersController->index(0, 50, '', '', '')
#9 /var/www/html/owncloud/lib/private/AppFramework/Http/Dispatcher.php(159): call_user_func_array(Array, Array)
#10 /var/www/html/owncloud/lib/private/AppFramework/Http/Dispatcher.php(89): OC\AppFramework\Http\Dispatcher->executeController(Object(OC\Settings\Controller\UsersController), 'index')
#11 /var/www/html/owncloud/lib/private/AppFramework/App.php(99): OC\AppFramework\Http\Dispatcher->dispatch(Object(OC\Settings\Controller\UsersController), 'index')
#12 /var/www/html/owncloud/lib/private/AppFramework/Routing/RouteActionHandler.php(46): OC\AppFramework\App::main('UsersController', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#13 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#14 /var/www/html/owncloud/lib/private/Route/Router.php(280): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
#15 /var/www/html/owncloud/lib/base.php(891): OC\Route\Router->match('/settings/users...')
#16 /var/www/html/owncloud/index.php(54): OC::handleRequest()
#17 {main}","File":"/var/www/html/owncloud/apps/user_ldap/lib/User/User.php","Line":117}","level":3,"time":"2017-05-03T11:18:09+00:00","method":"GET","url":"/owncloud/index.php/settings/users/users?offset=0&limit=50&gid=&pattern=","user":"password"}

```

```
select * from oc_ldap_user_mapping;
+--------------------------------------------------+---------------+----------------+
| ldap_dn                                          | owncloud_name | directory_uuid |
+--------------------------------------------------+---------------+----------------+
| uid=小池_憲明,ou=people,dc=owncloudqa,dc=com     |               | 小池           |
| uid=aaliyah_bähr,ou=people,dc=owncloudqa,dc=com  | aaliyah       | aaliyah        |
+--------------------------------------------------+---------------+----------------+
2 rows in set (0.00 sec)
````

**Comment by tomneedham** [comment]
http://php.net/manual/en/function.iconv.php

https://github.com/owncloud/core/blob/stable9.1/apps/user_ldap/lib/Access.php#L1110

> Since this version, the function returns FALSE on illegal characters, unless //IGNORE is specified in output charset. Before, it returned partial output string..

I tried input of username: 小池_憲明.

PHP gives me: `PHP Notice:  iconv(): Detected an illegal character in input string in /Users/tomneedham/encode.php on line 5` hence `$name` is set to false and evaluated as an empty string. 

Trying with `//IGNORE` as suggested in the manual...

**Comment by tomneedham** [comment]
... WIth `//IGNORE` we get an `_` correctly as the username

**Comment by jvillafanez** [comment]
I don't think we can have better solutions at the moment, so I'm fine with that. It's the current expectation. @tomneedham could you make a PR for it?

**Comment by butonic** [comment]
```
| ldapExpertUUIDUserAttr        | uid                                                                   |
| ldapExpertUsernameAttr        | uid                                                                   |

```
This is so wrong. At least `ldapExpertUUIDUserAttr` MUST be a UUID like attribute that contains values like `a4b234c6-d23c-1035-8c64-9bb74d28f7e6`, eg `objectguid` or `entryuuid` etc. username should also be a UUID attribute, we have seen cases where attributes like `uid` or `userPrincipalName` have changed over time. If admins want a readable home, that is what the home folder naming rule is for. If admins want users to be able with `uid` or `samaccountname` that is what `ldapLoginFilter` is for.

maybe @settermjd can clarify in the docs

**Comment by butonic** [comment]
also if i remember correctly the iconv was necessary to be able to use oc on windows / ntfs. linux filesystems have no problem storing these characters, AFAIK.
