### ISSUE TITLE
Failure in nightly in `configure-app-on-federated-server` pipeline

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/user_ldap#789]
The [nightly](https://drone.owncloud.com/owncloud/user_ldap/4539/62/16) is failing with following error

```bash
 cd /var/www/owncloud/federated
+ php occ market:install user_ldap
user_ldap: Installing new app ...
user_ldap: App installed.
+ bash /var/www/owncloud/server/apps/user_ldap/tests/acceptance/setConfig.sh
Cannot delete configuration with configID 'LDAPTestId'
An unhandled exception has been thrown:
TypeError: Return value of "OCA\User_LDAP\Command\DeleteConfig::execute()" must be of the type int, "null" returned. in /var/www/owncloud/federated/lib/composer/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#1 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#3 /var/www/owncloud/federated/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#4 /var/www/owncloud/federated/console.php(116): OC\Console\Application->run()
#5 /var/www/owncloud/federated/occ(11): require_once('/var/www/ownclo...')
#6 {main}Created new configuration with configID 'LDAPTestId'
An unhandled exception has been thrown:
TypeError: Return value of "OCA\User_LDAP\Command\SetConfig::execute()" must be of the type int, "null" returned. in /var/www/owncloud/federated/lib/composer/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#1 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#3 /var/www/owncloud/federated/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#4 /var/www/owncloud/federated/console.php(116): OC\Console\Application->run()
#5 /var/www/owncloud/federated/occ(11): require_once('/var/www/ownclo...')
#6 {main}An unhandled exception has been thrown:
TypeError: Return value of "OCA\User_LDAP\Command\SetConfig::execute()" must be of the type int, "null" returned. in /var/www/owncloud/federated/lib/composer/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#1 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#3 /var/www/owncloud/federated/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#4 /var/www/owncloud/federated/console.php(116): OC\Console\Application->run()
#5 /var/www/owncloud/federated/occ(11): require_once('/var/www/ownclo...')
#6 {main}An unhandled exception has been thrown:
TypeError: Return value of "OCA\User_LDAP\Command\SetConfig::execute()" must be of the type int, "null" returned. in /var/www/owncloud/federated/lib/composer/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#1 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#3 /var/www/owncloud/federated/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#4 /var/www/owncloud/federated/console.php(116): OC\Console\Application->run()
#5 /var/www/owncloud/federated/occ(11): require_once('/var/www/ownclo...')
#6 {main}An unhandled exception has been thrown:
TypeError: Return value of "OCA\User_LDAP\Command\SetConfig::execute()" must be of the type int, "null" returned. in /var/www/owncloud/federated/lib/composer/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#1 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#3 /var/www/owncloud/federated/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#4 /var/www/owncloud/federated/console.php(116): OC\Console\Application->run()
#5 /var/www/owncloud/federated/occ(11): require_once('/var/www/ownclo...')
#6 {main}An unhandled exception has been thrown:
TypeError: Return value of "OCA\User_LDAP\Command\SetConfig::execute()" must be of the type int, "null" returned. in /var/www/owncloud/federated/lib/composer/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#1 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#3 /var/www/owncloud/federated/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#4 /var/www/owncloud/federated/console.php(116): OC\Console\Application->run()
#5 /var/www/owncloud/federated/occ(11): require_once('/var/www/ownclo...')
#6 {main}An unhandled exception has been thrown:
TypeError: Return value of "OCA\User_LDAP\Command\SetConfig::execute()" must be of the type int, "null" returned. in /var/www/owncloud/federated/lib/composer/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#1 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#3 /var/www/owncloud/federated/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#4 /var/www/owncloud/federated/console.php(116): OC\Console\Application->run()
#5 /var/www/owncloud/federated/occ(11): require_once('/var/www/ownclo...')
#6 {main}An unhandled exception has been thrown:
TypeError: Return value of "OCA\User_LDAP\Command\SetConfig::execute()" must be of the type int, "null" returned. in /var/www/owncloud/federated/lib/composer/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#1 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#3 /var/www/owncloud/federated/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#4 /var/www/owncloud/federated/console.php(116): OC\Console\Application->run()
#5 /var/www/owncloud/federated/occ(11): require_once('/var/www/ownclo...')
#6 {main}An unhandled exception has been thrown:
TypeError: Return value of "OCA\User_LDAP\Command\SetConfig::execute()" must be of the type int, "null" returned. in /var/www/owncloud/federated/lib/composer/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#1 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#3 /var/www/owncloud/federated/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#4 /var/www/owncloud/federated/console.php(116): OC\Console\Application->run()
#5 /var/www/owncloud/federated/occ(11): require_once('/var/www/ownclo...')
#6 {main}An unhandled exception has been thrown:
TypeError: Return value of "OCA\User_LDAP\Command\SetConfig::execute()" must be of the type int, "null" returned. in /var/www/owncloud/federated/lib/composer/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#1 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#3 /var/www/owncloud/federated/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#4 /var/www/owncloud/federated/console.php(116): OC\Console\Application->run()
#5 /var/www/owncloud/federated/occ(11): require_once('/var/www/ownclo...')
#6 {main}An unhandled exception has been thrown:
TypeError: Return value of "OCA\User_LDAP\Command\SetConfig::execute()" must be of the type int, "null" returned. in /var/www/owncloud/federated/lib/composer/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#1 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#3 /var/www/owncloud/federated/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#4 /var/www/owncloud/federated/console.php(116): OC\Console\Application->run()
#5 /var/www/owncloud/federated/occ(11): require_once('/var/www/ownclo...')
#6 {main}An unhandled exception has been thrown:
TypeError: Return value of "OCA\User_LDAP\Command\SetConfig::execute()" must be of the type int, "null" returned. in /var/www/owncloud/federated/lib/composer/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#1 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#3 /var/www/owncloud/federated/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#4 /var/www/owncloud/federated/console.php(116): OC\Console\Application->run()
#5 /var/www/owncloud/federated/occ(11): require_once('/var/www/ownclo...')
#6 {main}An unhandled exception has been thrown:
TypeError: Return value of "OCA\User_LDAP\Command\SetConfig::execute()" must be of the type int, "null" returned. in /var/www/owncloud/federated/lib/composer/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#1 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#3 /var/www/owncloud/federated/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#4 /var/www/owncloud/federated/console.php(116): OC\Console\Application->run()
#5 /var/www/owncloud/federated/occ(11): require_once('/var/www/ownclo...')
#6 {main}An unhandled exception has been thrown:
TypeError: Return value of "OCA\User_LDAP\Command\SetConfig::execute()" must be of the type int, "null" returned. in /var/www/owncloud/federated/lib/composer/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#1 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#3 /var/www/owncloud/federated/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#4 /var/www/owncloud/federated/console.php(116): OC\Console\Application->run()
#5 /var/www/owncloud/federated/occ(11): require_once('/var/www/ownclo...')
#6 {main}An unhandled exception has been thrown:
TypeError: Return value of "OCA\User_LDAP\Command\SetConfig::execute()" must be of the type int, "null" returned. in /var/www/owncloud/federated/lib/composer/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#1 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#3 /var/www/owncloud/federated/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#4 /var/www/owncloud/federated/console.php(116): OC\Console\Application->run()
#5 /var/www/owncloud/federated/occ(11): require_once('/var/www/ownclo...')
#6 {main}An unhandled exception has been thrown:
TypeError: Return value of "OCA\User_LDAP\Command\SetConfig::execute()" must be of the type int, "null" returned. in /var/www/owncloud/federated/lib/composer/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#1 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#3 /var/www/owncloud/federated/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#4 /var/www/owncloud/federated/console.php(116): OC\Console\Application->run()
#5 /var/www/owncloud/federated/occ(11): require_once('/var/www/ownclo...')
#6 {main}An unhandled exception has been thrown:
TypeError: Return value of "OCA\User_LDAP\Command\SetConfig::execute()" must be of the type int, "null" returned. in /var/www/owncloud/federated/lib/composer/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#1 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#3 /var/www/owncloud/federated/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#4 /var/www/owncloud/federated/console.php(116): OC\Console\Application->run()
#5 /var/www/owncloud/federated/occ(11): require_once('/var/www/ownclo...')
#6 {main}An unhandled exception has been thrown:
TypeError: Return value of "OCA\User_LDAP\Command\SetConfig::execute()" must be of the type int, "null" returned. in /var/www/owncloud/federated/lib/composer/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#1 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#3 /var/www/owncloud/federated/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#4 /var/www/owncloud/federated/console.php(116): OC\Console\Application->run()
#5 /var/www/owncloud/federated/occ(11): require_once('/var/www/ownclo...')
#6 {main}An unhandled exception has been thrown:
TypeError: Return value of "OCA\User_LDAP\Command\SetConfig::execute()" must be of the type int, "null" returned. in /var/www/owncloud/federated/lib/composer/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#1 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#3 /var/www/owncloud/federated/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#4 /var/www/owncloud/federated/console.php(116): OC\Console\Application->run()
#5 /var/www/owncloud/federated/occ(11): require_once('/var/www/ownclo...')
#6 {main}An unhandled exception has been thrown:
TypeError: Return value of "OCA\User_LDAP\Command\SetConfig::execute()" must be of the type int, "null" returned. in /var/www/owncloud/federated/lib/composer/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#1 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#3 /var/www/owncloud/federated/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#4 /var/www/owncloud/federated/console.php(116): OC\Console\Application->run()
#5 /var/www/owncloud/federated/occ(11): require_once('/var/www/ownclo...')
#6 {main}An unhandled exception has been thrown:
TypeError: Return value of "OCA\User_LDAP\Command\SetConfig::execute()" must be of the type int, "null" returned. in /var/www/owncloud/federated/lib/composer/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#1 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#3 /var/www/owncloud/federated/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#4 /var/www/owncloud/federated/console.php(116): OC\Console\Application->run()
#5 /var/www/owncloud/federated/occ(11): require_once('/var/www/ownclo...')
#6 {main}An unhandled exception has been thrown:
TypeError: Return value of "OCA\User_LDAP\Command\SetConfig::execute()" must be of the type int, "null" returned. in /var/www/owncloud/federated/lib/composer/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#1 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#3 /var/www/owncloud/federated/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#4 /var/www/owncloud/federated/console.php(116): OC\Console\Application->run()
#5 /var/www/owncloud/federated/occ(11): require_once('/var/www/ownclo...')
#6 {main}An unhandled exception has been thrown:
TypeError: Return value of "OCA\User_LDAP\Command\SetConfig::execute()" must be of the type int, "null" returned. in /var/www/owncloud/federated/lib/composer/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#1 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#3 /var/www/owncloud/federated/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#4 /var/www/owncloud/federated/console.php(116): OC\Console\Application->run()
#5 /var/www/owncloud/federated/occ(11): require_once('/var/www/ownclo...')
#6 {main}An unhandled exception has been thrown:
TypeError: Return value of "OCA\User_LDAP\Command\SetConfig::execute()" must be of the type int, "null" returned. in /var/www/owncloud/federated/lib/composer/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#1 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#3 /var/www/owncloud/federated/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#4 /var/www/owncloud/federated/console.php(116): OC\Console\Application->run()
#5 /var/www/owncloud/federated/occ(11): require_once('/var/www/ownclo...')
#6 {main}An unhandled exception has been thrown:
TypeError: Return value of "OCA\User_LDAP\Command\SetConfig::execute()" must be of the type int, "null" returned. in /var/www/owncloud/federated/lib/composer/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#1 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#3 /var/www/owncloud/federated/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#4 /var/www/owncloud/federated/console.php(116): OC\Console\Application->run()
#5 /var/www/owncloud/federated/occ(11): require_once('/var/www/ownclo...')
#6 {main}An unhandled exception has been thrown:
TypeError: Return value of "OCA\User_LDAP\Command\SetConfig::execute()" must be of the type int, "null" returned. in /var/www/owncloud/federated/lib/composer/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#1 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#3 /var/www/owncloud/federated/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#4 /var/www/owncloud/federated/console.php(116): OC\Console\Application->run()
#5 /var/www/owncloud/federated/occ(11): require_once('/var/www/ownclo...')
#6 {main}An unhandled exception has been thrown:
TypeError: Return value of "OCA\User_LDAP\Command\SetConfig::execute()" must be of the type int, "null" returned. in /var/www/owncloud/federated/lib/composer/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#1 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#3 /var/www/owncloud/federated/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#4 /var/www/owncloud/federated/console.php(116): OC\Console\Application->run()
#5 /var/www/owncloud/federated/occ(11): require_once('/var/www/ownclo...')
#6 {main}An unhandled exception has been thrown:
TypeError: Return value of "OCA\User_LDAP\Command\SetConfig::execute()" must be of the type int, "null" returned. in /var/www/owncloud/federated/lib/composer/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#1 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#3 /var/www/owncloud/federated/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#4 /var/www/owncloud/federated/console.php(116): OC\Console\Application->run()
#5 /var/www/owncloud/federated/occ(11): require_once('/var/www/ownclo...')
#6 {main}An unhandled exception has been thrown:
TypeError: Return value of "OCA\User_LDAP\Command\SetConfig::execute()" must be of the type int, "null" returned. in /var/www/owncloud/federated/lib/composer/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#1 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#3 /var/www/owncloud/federated/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#4 /var/www/owncloud/federated/console.php(116): OC\Console\Application->run()
#5 /var/www/owncloud/federated/occ(11): require_once('/var/www/ownclo...')
#6 {main}An unhandled exception has been thrown:
TypeError: Return value of "OCA\User_LDAP\Command\SetConfig::execute()" must be of the type int, "null" returned. in /var/www/owncloud/federated/lib/composer/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#1 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#3 /var/www/owncloud/federated/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#4 /var/www/owncloud/federated/console.php(116): OC\Console\Application->run()
#5 /var/www/owncloud/federated/occ(11): require_once('/var/www/ownclo...')
#6 {main}An unhandled exception has been thrown:
TypeError: Return value of "OCA\User_LDAP\Command\SetConfig::execute()" must be of the type int, "null" returned. in /var/www/owncloud/federated/lib/composer/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#1 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#3 /var/www/owncloud/federated/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#4 /var/www/owncloud/federated/console.php(116): OC\Console\Application->run()
#5 /var/www/owncloud/federated/occ(11): require_once('/var/www/ownclo...')
#6 {main}An unhandled exception has been thrown:
TypeError: Return value of "OCA\User_LDAP\Command\SetConfig::execute()" must be of the type int, "null" returned. in /var/www/owncloud/federated/lib/composer/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#1 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/owncloud/federated/lib/composer/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#3 /var/www/owncloud/federated/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#4 /var/www/owncloud/federated/console.php(116): OC\Console\Application->run()
#5 /var/www/owncloud/federated/occ(11): require_once('/var/www/ownclo...')
#6 {main}
```

Related core issue: https://github.com/owncloud/core/issues/39630

**Comment by phil-davis** [comment]
Note to self: there might be some interactions to think about when the test pipelines are setting up an "old" federated server (based on Symfony 4) to test alongside a "new" local server (based on Symfony 5) - the set up process needs to be appropriate for each...

**Comment by phil-davis** [comment]
Note: it only fails for the `core-apiAll` pipelines that run with core master.
The pipelines the run with core `latest` (10.12.1) are passing - I suppose that is expected because any existing Symfony4 code in user_ldap will be working fine with core 10.12.1.

**Comment by phil-davis** [comment]
To install user_lap on the federated server, the CI does:
```
cd /var/www/owncloud/federated
php occ market:install user_ldap
```

So it installs the existing released user_ldap app (Symfony 4 code), and tries to used it on the federated server that is running core `daily-master-qa` (Symfony 5). That, of course, does not work.

It is probably better to run the federated server with `latest` core 10.12.1 (Symfony 4) and run the "local" server with `daily-master-qa` (Symfony 5). Doing that will also demonstrate that a new Symfony 5 system can stll "talk" federated sharing to a federated 10.12.1 server that is using Symfony 4.
