### ISSUE TITLE
add ldap user results in exception screen

### ISSUE THREAD

**Issue by paulgiordano** [owncloud/user_ldap#802]
When I add a new user to LDAP and sync the Users, attempt to logon, and get the exception screen, along with the following logs:

```
{"reqId":"XdortKi6vVgm3342sRdi","level":3,"time":"2023-08-18T12:18:16+00:00","remoteAddr":"10.4.0.57","user":"D5400072-43E0-4564-8F0D-C7FD2446AF93","app":"OC\\Files\\Filesystem","method":"POST","url":"\/index.php\/login","message":"Backends provided no user object for 2438783D-55C9-4E6B-AC12-BD894D25D30C"}
{"reqId":"XdortKi6vVgm3342sRdi","level":3,"time":"2023-08-18T12:18:16+00:00","remoteAddr":"10.4.0.57","user":"D5400072-43E0-4564-8F0D-C7FD2446AF93","app":"PHP","method":"POST","url":"\/index.php\/login","message":"Undefined variable: rootPath at \/var\/www\/html\/owncloud\/apps\/files_sharing\/lib\/SharedStorage.php#98"}
{"reqId":"XdortKi6vVgm3342sRdi","level":3,"time":"2023-08-18T12:18:16+00:00","remoteAddr":"10.4.0.57","user":"D5400072-43E0-4564-8F0D-C7FD2446AF93","app":"PHP","method":"POST","url":"\/index.php\/login","message":"Undefined property: OCA\\Files_Sharing\\SharedStorage::$ at \/var\/www\/html\/owncloud\/apps\/files_sharing\/lib\/SharedStorage.php#98"}
{"reqId":"XdortKi6vVgm3342sRdi","level":3,"time":"2023-08-18T12:18:16+00:00","remoteAddr":"10.4.0.57","user":"D5400072-43E0-4564-8F0D-C7FD2446AF93","app":"PHP","method":"POST","url":"\/index.php\/login","message":"Undefined variable: rootPath at \/var\/www\/html\/owncloud\/apps\/files_sharing\/lib\/SharedStorage.php#98"}
{"reqId":"XdortKi6vVgm3342sRdi","level":3,"time":"2023-08-18T12:18:16+00:00","remoteAddr":"10.4.0.57","user":"D5400072-43E0-4564-8F0D-C7FD2446AF93","app":"PHP","method":"POST","url":"\/index.php\/login","message":"Undefined property: OCA\\Files_Sharing\\SharedStorage::$ at \/var\/www\/html\/owncloud\/apps\/files_sharing\/lib\/SharedStorage.php#98"}
{"reqId":"XdortKi6vVgm3342sRdi","level":3,"time":"2023-08-18T12:18:16+00:00","remoteAddr":"10.4.0.57","user":"D5400072-43E0-4564-8F0D-C7FD2446AF93","app":"OC\\Files\\Filesystem","method":"POST","url":"\/index.php\/login","message":"Backends provided no user object for 2438783D-55C9-4E6B-AC12-BD894D25D30C"}
{"reqId":"XdortKi6vVgm3342sRdi","level":3,"time":"2023-08-18T12:18:16+00:00","remoteAddr":"10.4.0.57","user":"D5400072-43E0-4564-8F0D-C7FD2446AF93","app":"PHP","method":"POST","url":"\/index.php\/login","message":"Undefined variable: rootPath at \/var\/www\/html\/owncloud\/apps\/files_sharing\/lib\/SharedStorage.php#98"}
{"reqId":"XdortKi6vVgm3342sRdi","level":3,"time":"2023-08-18T12:18:16+00:00","remoteAddr":"10.4.0.57","user":"D5400072-43E0-4564-8F0D-C7FD2446AF93","app":"PHP","method":"POST","url":"\/index.php\/login","message":"Undefined property: OCA\\Files_Sharing\\SharedStorage::$ at \/var\/www\/html\/owncloud\/apps\/files_sharing\/lib\/SharedStorage.php#98"}
{"reqId":"XdortKi6vVgm3342sRdi","level":3,"time":"2023-08-18T12:18:16+00:00","remoteAddr":"10.4.0.57","user":"D5400072-43E0-4564-8F0D-C7FD2446AF93","app":"PHP","method":"POST","url":"\/index.php\/login","message":"Undefined variable: rootPath at \/var\/www\/html\/owncloud\/apps\/files_sharing\/lib\/SharedStorage.php#98"}
{"reqId":"XdortKi6vVgm3342sRdi","level":3,"time":"2023-08-18T12:18:16+00:00","remoteAddr":"10.4.0.57","user":"D5400072-43E0-4564-8F0D-C7FD2446AF93","app":"PHP","method":"POST","url":"\/index.php\/login","message":"Undefined property: OCA\\Files_Sharing\\SharedStorage::$ at \/var\/www\/html\/owncloud\/apps\/files_sharing\/lib\/SharedStorage.php#98"}
{"reqId":"XdortKi6vVgm3342sRdi","level":3,"time":"2023-08-18T12:18:16+00:00","remoteAddr":"10.4.0.57","user":"D5400072-43E0-4564-8F0D-C7FD2446AF93","app":"PHP","method":"POST","url":"\/index.php\/login","message":"Undefined variable: rootPath at \/var\/www\/html\/owncloud\/apps\/files_sharing\/lib\/SharedStorage.php#98"}
{"reqId":"XdortKi6vVgm3342sRdi","level":3,"time":"2023-08-18T12:18:16+00:00","remoteAddr":"10.4.0.57","user":"D5400072-43E0-4564-8F0D-C7FD2446AF93","app":"PHP","method":"POST","url":"\/index.php\/login","message":"Undefined property: OCA\\Files_Sharing\\SharedStorage::$ at \/var\/www\/html\/owncloud\/apps\/files_sharing\/lib\/SharedStorage.php#98"}
{"reqId":"XdortKi6vVgm3342sRdi","level":3,"time":"2023-08-18T12:18:16+00:00","remoteAddr":"10.4.0.57","user":"D5400072-43E0-4564-8F0D-C7FD2446AF93","app":"PHP","method":"POST","url":"\/index.php\/login","message":"Undefined variable: rootPath at \/var\/www\/html\/owncloud\/apps\/files_sharing\/lib\/SharedStorage.php#98"}
{"reqId":"XdortKi6vVgm3342sRdi","level":3,"time":"2023-08-18T12:18:16+00:00","remoteAddr":"10.4.0.57","user":"D5400072-43E0-4564-8F0D-C7FD2446AF93","app":"PHP","method":"POST","url":"\/index.php\/login","message":"Undefined property: OCA\\Files_Sharing\\SharedStorage::$ at \/var\/www\/html\/owncloud\/apps\/files_sharing\/lib\/SharedStorage.php#98"}
{"reqId":"XdortKi6vVgm3342sRdi","level":3,"time":"2023-08-18T12:18:16+00:00","remoteAddr":"10.4.0.57","user":"D5400072-43E0-4564-8F0D-C7FD2446AF93","app":"PHP","method":"POST","url":"\/index.php\/login","message":"Undefined variable: rootPath at \/var\/www\/html\/owncloud\/apps\/files_sharing\/lib\/SharedStorage.php#98"}
{"reqId":"XdortKi6vVgm3342sRdi","level":3,"time":"2023-08-18T12:18:16+00:00","remoteAddr":"10.4.0.57","user":"D5400072-43E0-4564-8F0D-C7FD2446AF93","app":"PHP","method":"POST","url":"\/index.php\/login","message":"Undefined property: OCA\\Files_Sharing\\SharedStorage::$ at \/var\/www\/html\/owncloud\/apps\/files_sharing\/lib\/SharedStorage.php#98"}
{"reqId":"XdortKi6vVgm3342sRdi","level":3,"time":"2023-08-18T12:18:16+00:00","remoteAddr":"10.4.0.57","user":"D5400072-43E0-4564-8F0D-C7FD2446AF93","app":"PHP","method":"POST","url":"\/index.php\/login","message":"Undefined variable: rootPath at \/var\/www\/html\/owncloud\/apps\/files_sharing\/lib\/SharedStorage.php#98"}
{"reqId":"XdortKi6vVgm3342sRdi","level":3,"time":"2023-08-18T12:18:16+00:00","remoteAddr":"10.4.0.57","user":"D5400072-43E0-4564-8F0D-C7FD2446AF93","app":"PHP","method":"POST","url":"\/index.php\/login","message":"Undefined property: OCA\\Files_Sharing\\SharedStorage::$ at \/var\/www\/html\/owncloud\/apps\/files_sharing\/lib\/SharedStorage.php#98"}
{"reqId":"XdortKi6vVgm3342sRdi","level":3,"time":"2023-08-18T12:18:16+00:00","remoteAddr":"10.4.0.57","user":"D5400072-43E0-4564-8F0D-C7FD2446AF93","app":"PHP","method":"POST","url":"\/index.php\/login","message":"Undefined variable: rootPath at \/var\/www\/html\/owncloud\/apps\/files_sharing\/lib\/SharedStorage.php#98"}
{"reqId":"XdortKi6vVgm3342sRdi","level":3,"time":"2023-08-18T12:18:16+00:00","remoteAddr":"10.4.0.57","user":"D5400072-43E0-4564-8F0D-C7FD2446AF93","app":"PHP","method":"POST","url":"\/index.php\/login","message":"Undefined property: OCA\\Files_Sharing\\SharedStorage::$ at \/var\/www\/html\/owncloud\/apps\/files_sharing\/lib\/SharedStorage.php#98"}
{"reqId":"XdortKi6vVgm3342sRdi","level":3,"time":"2023-08-18T12:18:16+00:00","remoteAddr":"10.4.0.57","user":"D5400072-43E0-4564-8F0D-C7FD2446AF93","app":"PHP","method":"POST","url":"\/index.php\/login","message":"Undefined variable: rootPath at \/var\/www\/html\/owncloud\/apps\/files_sharing\/lib\/SharedStorage.php#98"}
{"reqId":"XdortKi6vVgm3342sRdi","level":3,"time":"2023-08-18T12:18:16+00:00","remoteAddr":"10.4.0.57","user":"D5400072-43E0-4564-8F0D-C7FD2446AF93","app":"PHP","method":"POST","url":"\/index.php\/login","message":"Undefined property: OCA\\Files_Sharing\\SharedStorage::$ at \/var\/www\/html\/owncloud\/apps\/files_sharing\/lib\/SharedStorage.php#98"}
{"reqId":"XdortKi6vVgm3342sRdi","level":3,"time":"2023-08-18T12:18:16+00:00","remoteAddr":"10.4.0.57","user":"D5400072-43E0-4564-8F0D-C7FD2446AF93","app":"PHP","method":"POST","url":"\/index.php\/login","message":"Undefined variable: rootPath at \/var\/www\/html\/owncloud\/apps\/files_sharing\/lib\/SharedStorage.php#98"}
{"reqId":"XdortKi6vVgm3342sRdi","level":3,"time":"2023-08-18T12:18:16+00:00","remoteAddr":"10.4.0.57","user":"D5400072-43E0-4564-8F0D-C7FD2446AF93","app":"PHP","method":"POST","url":"\/index.php\/login","message":"Undefined property: OCA\\Files_Sharing\\SharedStorage::$ at \/var\/www\/html\/owncloud\/apps\/files_sharing\/lib\/SharedStorage.php#98"}
{"reqId":"XdortKi6vVgm3342sRdi","level":3,"time":"2023-08-18T12:18:16+00:00","remoteAddr":"10.4.0.57","user":"D5400072-43E0-4564-8F0D-C7FD2446AF93","app":"index","method":"POST","url":"\/index.php\/login","message":"Exception: {\"Exception\":\"InvalidArgumentException\",\"Message\":\"Jail rootPath is null\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Jail.php(473): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Jail->getSourcePath()\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/SharedStorage.php(380): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Jail->resolvePath()\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(598): OCA\\\\Files_Sharing\\\\SharedStorage->acquireLock()\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(2044): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock()\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(2147): OC\\\\Files\\\\View->lockPath()\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1211): OC\\\\Files\\\\View->lockFile()\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(280): OC\\\\Files\\\\View->basicOperation()\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/public\\\/Events\\\/EventEmitterTrait.php(50): OC\\\\Files\\\\View->OC\\\\Files\\\\{closure}(*** sensitive parameters replaced ***)\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(282): OC\\\\Files\\\\View->emittingCall()\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Folder.php(158): OC\\\\Files\\\\View->mkdir()\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/util.php(425): OC\\\\Files\\\\Node\\\\Folder->newFolder()\\n#11 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/util.php(403): OC_Util::copyr()\\n#12 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(469): OC_Util::copySkeleton()\\n#13 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(1036): OC\\\\User\\\\Session->prepareUserLogin()\\n#14 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(543): OC\\\\User\\\\Session->loginInOwnCloud(*** sensitive parameters replaced ***)\\n#15 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(344): OC\\\\User\\\\Session->loginWithPassword(*** sensitive parameters replaced ***)\\n#16 \\\/var\\\/www\\\/html\\\/owncloud\\\/core\\\/Controller\\\/LoginController.php(270): OC\\\\User\\\\Session->login(*** sensitive parameters replaced ***)\\n#17 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(169): OC\\\\Core\\\\Controller\\\\LoginController->tryLogin(*** sensitive parameters replaced ***)\\n#18 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController()\\n#19 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(99): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch()\\n#20 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main()\\n#21 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(344): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke()\\n#22 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(913): OC\\\\Route\\\\Router->match()\\n#23 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#24 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Jail.php\",\"Line\":56}"}
```

This started happening out of the blue. I'm responsible for the Linux system, and I've verified that no changes were made to it. What else can I Provide? I have a gist: https://gist.github.com/paulgiordano/c6e38a769a23df232b1ea8b491985219

**Comment by paulgiordano** [comment]
Lots of digging. In View.php function lockPath - some debugging code, and the line: $mount->getInternalPath($absolutePath) returns a blank path. The actual absolutePath is "/D5400072-43E0-4564-8F0D-C7FD2446AF93/files/Documents"

So the call to Jail.php that gets the mkdir command gets an empty path.

**Comment by paulgiordano** [comment]
So I create a directory like above, and voila it works. So something with the mkdir thing?
